# Generated by Django 2.0.5 on 2018-05-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1, max_length=1, verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(blank=True, default='未注册真实姓名 ', max_length=50, verbose_name='真实姓名'),
        ),
    ]
