# Generated by Django 2.0.5 on 2018-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180510_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, '司机'), (2, '会计'), (3, '管理员')], default=1, verbose_name='用户角色'),
        ),
    ]
