# Generated by Django 2.0.4 on 2018-12-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180510_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='realname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='nikename',
            field=models.CharField(blank=True, max_length=50, verbose_name='昵称'),
        ),
    ]
