# Generated by Django 2.0.4 on 2018-12-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181210_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nikename',
            new_name='nickname',
        ),
    ]
