# Generated by Django 2.0.4 on 2018-12-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181210_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='昵称'),
        ),
    ]
