# Generated by Django 2.0.5 on 2018-05-09 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('bxno', models.BigAutoField(primary_key=True, serialize=False, verbose_name='报销编号')),
                ('title', models.CharField(max_length=20, verbose_name='报销事项')),
                ('carNo', models.CharField(max_length=20, verbose_name='车牌号')),
                ('text', models.TextField(verbose_name='备注')),
                ('amout', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金额')),
                ('img', models.ImageField(upload_to='img', verbose_name='发票图片')),
                ('wipeout', models.BooleanField(default=False, verbose_name='核销状态')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '报销详情表',
                'verbose_name_plural': '报销详情表',
            },
        ),
    ]
