# Generated by Django 2.0.5 on 2018-05-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freightcost', '0002_auto_20180515_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='img',
            field=models.ImageField(upload_to='static/media/img', verbose_name='发票图片'),
        ),
    ]
