# Generated by Django 2.0.4 on 2018-12-10 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freightcost', '0004_auto_20180515_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_img', models.ImageField(upload_to='media/skins', verbose_name='皮肤')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '皮肤',
                'verbose_name_plural': '皮肤',
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
